# config/routes.yaml

# Define routes for the CustomerController
customer_routes:
    path: /api/v1/customers
    controller: 'App\Controller\CustomerController::index'
    methods: ['GET']

customer_show:
    path: /api/v1/customers/{id}
    controller: 'App\Controller\CustomerController::show'
    methods: ['GET']
    requirements:
        id: '\d+' # Match numeric IDs only

customer_create:
    path: /api/v1/customers
    controller: 'App\Controller\CustomerController::create'
    methods: ['POST']

customer_update:
    path: /api/v1/customers/{id}
    controller: 'App\Controller\CustomerController::update'
    methods: ['PUT']
    requirements:
        id: '\d+' # Match numeric IDs only

customer_delete:
    path: /api/v1/customers/{id}
    controller: 'App\Controller\CustomerController::delete'
    methods: ['DELETE']
    requirements:
        id: '\d+' # Match numeric IDs only
login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['POST']