<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240216124327 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Insert initial data into login table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE login (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            email VARCHAR(180) NOT NULL,
            roles JSON NOT NULL,
            password VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        )');

        // Insert initial user data
        $email = $this->connection->quote('admin@example.com');
        $roles = $this->connection->quote(json_encode(['ROLE_ADMIN']));
        $password = password_hash('password', PASSWORD_DEFAULT);

        $this->addSql('INSERT INTO login (email, roles, password) VALUES (:email, :roles, :password)', [
            'email' => $email,
            'roles' => $roles,
            'password' => $password,
        ]);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE login');
    }
}
